document.write('		<header id="header">');
document.write('			<a href="index.html">');
document.write('				<div id="logo">');
document.write('					<img src="images/logos/johnodonovan.png" width="167px" height="200" alt="profile picture"/>');
document.write('				</div>');
document.write('			</a>');
document.write('				<div id="title_div">	');
document.write('			<span id="name_span">John O\'Donovan </span>  &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp ');
document.write('			Department of Computer Science, University of California, Santa Barbara		');
document.write('			 </div>');
document.write('			 <div id="intro_text_div">I am an associate research scientist at the Computer Science dept., UCSB, where I co-direct the <a href="http://ilab.cs.ucsb.edu">4Eyes research lab</a>. My research background is in AI, with focus on recommender systems.  I have a particular interest in human-computer interaction aspects of these systems --for example, learning how an interaction design impacts human trust in an algorithm over time. 	I am also a co-founder of <a href=http://www.sirassystems.com>Siras Systems Inc.</a>, and director of AI and Machine Learning at <a href="https://intouchhealth.com/">InTouch Health Inc.</a>	');
document.write('			   <div id="ucsb_logo"><img src="images/logos/ucsb.png" alt="ucsb" />');
document.write('			</div>');
document.write('			 <div id="contact_text_div1">Email: jod@cs.ucsb.edu	  ');
document.write('			 <div id="contact_text_div2">Office: Room 101, Building 935.');
document.write('			 <div id="contact_text_div3">Fax:  (805) 893-8553	  ');
document.write('			 <div id="contact_text_div4">Office Hours: 2-3pm Mon/Thur	  ');
document.write('			 </div> 	');		
document.write('		</header>');
