document.write('		<header id="header">');
document.write('			<a href="index.html">');
document.write('				<div id="logo">');
document.write('					<img src="images/logos/profile-pic-jod-175.png" alt="profile picture"/>');
document.write('				</div>');
document.write('			</a>');
document.write('				<div id="title_div">	');
document.write('			<span id="name_span">John O\'Donovan </span>  &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp ');
document.write('			Department of Computer Science, University of California, Santa Barbara		');
document.write('			 </div>');
document.write('			 <div id="intro_text_div">I am an associate research scientist at the Computer Science dept., UCSB. My research background is in AI, with focus on recommender systems.  I have a particular interest in human-computer interaction aspects of these systems --for example, learning how a particular interaction design impacts human trust in an algorithm over time. 	I am also a co-founder and CTO of <a href=http://www.sirassystems.com>Siras Systems Inc.</a>, providers of personalized educational planning and reporting.	  ');
document.write('			   <div id="ucsb_logo"><img src="images/logos/ucsb.png" alt="ucsb" />');
document.write('			</div>');
document.write('			 <div id="contact_text_div1">Email: jod@cs.ucsb.edu	  ');
document.write('			 <div id="contact_text_div2">Office: Room 101, Building 935.');
document.write('			 <div id="contact_text_div3">Fax:  (805) 893-8553	  ');
document.write('			 <div id="contact_text_div4">Office Hours: 2-3pm Mon/Thur	  ');
document.write('			   </div> 	');		
document.write('		</header>');
